Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/12/2023
Var
   M  :INTEIRO

Inicio
   ESCREVAL("DIGITE A MEDIDA EM METROS: ")
   LEIA(M)
   escreval("==============================")

   ESCREVAL("A MEDIDA DE ", M, "m É IGUAL A: ", M*100, "cm" )
   escreval("===================================")


Fimalgoritmo