Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/12/2023
Var
D:INTEIRO


Inicio
ESCREVAL("DIGITE UM VALOR EM MILHA: ")
LEIA(D)
escreval("===============================")

ESCREVAL(D , " MILHAS CORESPONDE A", 0.6214*D, "km" )
escreval("===============================")

Fimalgoritmo