Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/01/2024
Var
   n:inteiro

Inicio
   escreva("Digite um número: ")
   leia(n)

   se(n > 0) entao
      escreva("O número é positivo! ")

   senao

      se(n = 0) entao
         escreva("O número é neutro! ")

      senao
         escreva("O número é negativo! ")

      fimse
   fimse

Fimalgoritmo