Algoritmo "Resto_da_divisão"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/01/2024
Var
 n, d:inteiro

Inicio
escreva("Digite o numerador: ")
leia(n)

escreva("Digite o denominador: ")
leia(d)

se (d = 0) entao
escreva("Não é possivel fazer essa divisão!")

senao

se (n % d = 0) entao
escreva("É divisivel!")

senao
escreva("Não é divisivel!")

fimse
fimse

Fimalgoritmo