Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/12/2023
Var
x:inteiro

Inicio
escreval("DIGITE O VALOR DO SE SALÁRIO: ")
LEIA(x)
escreval("======================================================")

escreval("O NOVO SALÁRIO COM O REAJUSTE DE 15% E DE: ", (x+x*0.15), "R$")
escreval("======================================================")


Fimalgoritmo