Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/12/2023
Var
x:inteiro


Inicio
escreval("DIGITE O VALOR DO DEPÓSITO: ")
LEIA(x)
escreval("=====================================================")

escreval("O NOVO VALOR COM O RENDIMENTO DE 5% E DE: ", (x+x*0.05), "R$")
escreval("=====================================================")

Fimalgoritmo